### ISSUE TITLE
 Type 'AngularPlugin' is not assignable to type 'ITelemetryPlugin', Angular 15 ( "@angular/common": "15.1.0") error when trying to build the project

### ISSUE THREAD

**Issue by hladysh** [microsoft/applicationinsights-angularplugin-js#97]
error TS2322: Type 'AngularPlugin' is not assignable to type 'ITelemetryPlugin'.
  Types of property 'setNextPlugin' are incompatible.

import { AngularPlugin } from '@microsoft/applicationinsights-angularplugin-js';

        const angularPlugin = new AngularPlugin();
        this.appInsights = new ApplicationInsights({
            config: {
                instrumentationKey: 'key',
                enableAutoRouteTracking: false, // option to log all route changes
                enableCorsCorrelation: true,
                extensions: [angularPlugin],
                extensionConfig: {
                    [angularPlugin.identifier]: { router: this.router },
                },
            },
        });
        this.appInsights.loadAppInsights();

    extensions: [angularPlugin],
                                ~~~~~~~~~~~~~



 "@microsoft/applicationinsights-angularplugin-js": "3.0.1",
 "@microsoft/applicationinsights-web": "2.8.9",
 "@angular/common": "15.1.0",
 "typescript": "4.9.4",

**Comment by MSNev** [comment]
Which versions of the plugin and ApplicationInsights are you using?

We recently release v3.0.1 of the angular plugin which moved the base version of Application Insights to 2.8.10 to address this issue (which is typescript being more pedantic than necessary) #76

You can safely cast to any to bypass the error, we believe we tracked this down to a change we made to introduce an optional `unload` function. As we support backward compatibility of the newer ApplicationInsights using older components (plugins).

If your not using 3.0.1 and 2.8.10 can you please upgrade both (or use the workaround by casting as any to avoid TypeScript complaining).

**Comment by hladysh** [comment]
problem was fixed after the update "@microsoft/applicationinsights-web": "2.8.9", to "@microsoft/applicationinsights-web": "2.8.10"

**Comment by OzBob** [comment]
@MSNev the dependencies between the 2 projects are inconsistent.
Will these old versions ^2.8.12 be upgraded to ^3.0.1?
https://github.com/microsoft/applicationinsights-angularplugin-js/blob/main/package.json#L67
```
   "@microsoft/applicationinsights-common": "^2.8.12",
    "@microsoft/applicationinsights-core-js": "^2.8.12",
    "@microsoft/applicationinsights-properties-js": "^2.8.12",
```

To match the dependencies of '@microsoft/applicationinsights-web'? i.e. v3.0.1?

For now I will experiment and **downgrade** @microsoft/applicationinsights-web to v2.8.13

**Comment by psiservices-dbrink** [comment]
Is there any update?  This still occurs when using the most current version of both these packages

```
    "@microsoft/applicationinsights-angularplugin-js": "^3.0.1",
    "@microsoft/applicationinsights-web": "^3.0.2",
```

**Comment by MSNev** [comment]
Still in progress (sorry delay as I was OOF last week), the plan is to finalize the updates and release the update by / before the end of July 23.

**Comment by psiservices-dbrink** [comment]
That's unfortunate a seemingly small issue with dependency versions has lingered for so long.  You're aware Angular 16 has been out for three months already?

**Comment by siyuniu-ms** [comment]
for angular v14, the bug is solved at ver 14.0.0 https://github.com/microsoft/applicationinsights-angularplugin-js/releases/tag/14.0.0

**Comment by yellowjacketcoder** [comment]
This issue has been revived because of another update of the `@microsoft/applicationinsights-web` package. v3.3.9 is the latest (published 2 hrs ago as of writing) but v3.3.8 broke the typings as well. I suspect that's just due to the outdated dependencies in this package. Can we get an update?

**Comment by blazekv** [comment]
I have same issue with this versions
```
    "@microsoft/applicationinsights-angularplugin-js": "15.3.8",
    "@microsoft/applicationinsights-web": "3.3.10",
```
